baseURL = "http://www.philipbradley.net/"
languageCode = "en-us"
title = "Philip Bradley"
theme = "bare"
enableGitInfo = true






[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["posts"]
author = "Philip Bradley"
email = "nope@example.com"
# repoLink = "https://github.com/orf/bare-hugo-theme"
description = 'Just some guy with glasses'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution = true

[[params.social]]
icon = "github-circle"
url = "https://github.com/orf/"
